#!/usr/bin/bash

touch logs.txt
mkdir -p data
touch data/users.csv
touch data/products.csv
touch data/codes.csv
touch data/transactions.csv
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
python3 src/main.py
deactivate
